### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by samrafanoe** [SpiderLabs/social_mapper#93] opened 2018-11-18 08:45 UTC
AttributeError: 'module' object has no attribute '_base'

**Comment by samrafanoe** [comment] 2018-11-18 08:51
python social_mapper.py -f company -i "SpiderLabs" -m accurate -a -t strict

> Traceback (most recent call last):
  File "social_mapper.py", line 2, in <module>
    from modules import facebookfinder
  File "/home/samrafanoe/project/social_mapper/modules/facebookfinder.py", line 9, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 311, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by Green-Wolf** [comment] 2018-11-20 17:54
Hi there, have you installed all the requirements in the requirements.txt file? Also there isn't actually a company on linkedin called Spiderlabs, so that might be causing the error. Have you tried on one you know exists?

**Comment by Green-Wolf** [comment] 2018-12-03 10:48
Closing this as I couldn't reproduce, most likely a requirement issue.

**Closed by Green-Wolf** 2018-12-03 10:48 UTC
