### ISSUE TITLE
Error when running with -f socialmapper

### ISSUE THREAD

**Issue by willothewasp** [SpiderLabs/social_mapper#91] opened 2018-11-15 21:45 UTC
Using `-f socialmapper` and an `html` file doesn't work for me.
As an example, running this:
`python2 social_mapper.py -f company -i <company_name> -m fast -li`
And after that the following:
`python2 social_mapper.py -f socialmapper -i ./SM-Results/<file_name>.html -m fast -fb`
Yields this:
```
Backup of original report created: 'SM-Results/backup.html'
Traceback (most recent call last):

  File "social_mapper.py", line 1073, in <module>
    urllib.urlretrieve(person_image, "temp-targets/" + full_name + ".jpg")
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 469, in open_file
    return self.open_local_file(url)
  File "/usr/lib/python2.7/urllib.py", line 483, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: 'None'
```

**Comment by Green-Wolf** [comment] 2018-11-20 17:56
Thanks for letting me know, I'll have a look into this when i have some time

**Comment by e-Euler** [comment] 2018-12-18 19:09
@willothewasp could you please provide the target so I can check the target image url format?

**Comment by Green-Wolf** [comment] 2019-01-15 11:41
Closing as was not able to reproduce.

**Closed by Green-Wolf** 2019-01-15 11:41 UTC
